In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings('ignore')

apart_df = pd.read_csv('C:/Users/hojys/workspace/ml_python/apart/K_20200425_sumVariable.csv', encoding='euc-kr')

#display(apart_df.head()) # 데이터 읽히는지 확인 -> 로드 완료
#display(apart_df.isnull().sum()) # null 확인 -> Null 0개 확인
print(apart_df.columns)

Index(['gu', 'address', 'Apart', 'pps', 'dong', 'size', 'floor', 'year',
       'long', 'lat', 'dist_from_mart.x', 'dist_from_department',
       'dist_from_mart.y', 'dist_from_highschool',
       'dist_from_elementaryschool', 'dist_from_univ',
       'dist_from_middleschool', 'dist_from_bus', 'dist_from_hospital',
       'dist_from_academy', 'crime', 'arrest', 'foreigner', 'trash', 'cctv',
       'dist_from_subway', 'dist_from_kinder', 'dist_from_park', 'out', 'in',
       'popu'],
      dtype='object')


In [4]:
#라벨링 작업
print(apart_df.dtypes)
#pd.get_dummies(apart_df)
#address = apart_df.dong.unique() #컬럼별 유니크값 확인
#print(list(address)) # 축약된 컬럼명 확인 

#딕셔너리화한 데이터
gu_dict = {'강남구':1, '강동구':2, '강북구':3, '강서구':4, '관악구':5, '광진구':6, '구로구':7, '금천구':8, '노원구':9, '도봉구':10,
           '동대문구':11, '동작구':12, '마포구':13, '서대문구':14, '서초구':15, '성동구':16, '성북구':17, '송파구':18, '양천구':19,
           '영등포구':20, '용산구':21, '은평구':22, '종로구':23, '중구':24, '중랑구':25}

dong_dict = {'개포동':1, '도곡동':2, '세곡동':3, '일원동':4, '자곡동':5, '삼성동':6, '논현동':7,
  '수서동':8, '청담동':9, '압구정동':10, '역삼동':11, '신사동':12, '대치동':13, '율현동':14,
  '암사동':15, '고덕동':16, '상일동':17, '천호동':18, '둔촌동':19, '성내동':20, '강일동':22,
  '명일동':23, '길동':24, '수유동':25, '미아동':26, '번동':27, '우이동':28, '방화동':29,
  '화곡동':30, '마곡동':31, '내발산동':32, '가양동':33, '등촌동':34, '공항동':35, '염창동':36,
  '신림동':37, '봉천동':38, '남현동':39, '구의동':40, '자양동':41, '화양동':42, '광장동':43,
  '중곡동':44, '군자동':45, '구로동':46, '고척동':47, '개봉동':48, '오류동':49, '신도림동':50,
  '궁동':51, '항동':52, '온수동':53, '천왕동':54, '가리봉동':55, '가산동':56, '시흥동':57,
  '독산동':58, '상계동':59, '월계동':60, '공릉동':61, '중계동':62, '하계동':63, '쌍문동':64,
  '창동':66, '방학동':67, '도봉동':68, '전농동':69, '이문동':70, '장안동':71, '답십리동':72, 
  '휘경동':73, '용두동':74, '회기동':75, '제기동':76, '청량리동':77, '신설동':78, '사당동':79, 
  '상도동':80, '노량진동':81, '흑석동':82, '본동':83, '대방동':84, '신대방동':85, '동작동':86, 
  '상도1동':87, '신공덕동':88, '공덕동':89, '대흥동':90, '신수동':91, '서교동':92, '신정동':93, 
  '도화동':94, '용강동':95, '창전동':96, '상수동':97, '상암동':98, '마포동':99, '성산동':100, 
  '노고산동':101, '아현동':102, '염리동':103, '중동':104, '현석동':105, '연남동':106, '토정동':107, 
  '합정동':108, '망원동':109, '하중동':110, '연희동':111, '홍은동':112, '현저동':113, '냉천동':114, 
  '남가좌동':115, '홍제동':116, '영천동':117, '북가좌동':118, '북아현동':119, '대현동':120, 
  '충정로3가':121, '충정로2가':122, '미근동':123, '창천동':124, '천연동':125, '합동':126, '방배동':127, 
  '서초동':128, '반포동':129, '우면동':130, '양재동':131, '신원동':132, '잠원동':133, '내곡동':134, 
  '성수동1가':135, '행당동':136, '옥수동':137, '성수동2가':138, '금호동1가':139, '금호동4가':140, 
  '용답동':141, '응봉동':142, '금호동2가':143, '마장동':144, '금호동3가':145, '사근동':146, '송정동':147, 
  '홍익동':148, '상왕십리동':149, '하왕십리동':150, '도선동':151, '돈암동':152, '길음동':153, '정릉동':154, 
  '삼선동2가':155, '종암동':156, '석관동':157, '보문동3가':158, '동소문동4가':159, '장위동':160, 
  '동소문동7가':161, '하월곡동':162, '동선동1가':163, '동선동3가':164, '삼선동3가':165, '동선동4가':166, 
  '안암동1가':167, '성북동':168, '삼선동4가':169, '동선동5가':170, '상월곡동':171, '안암동4가':172, 
  '안암동3가':173, '동소문동5가':174, '보문동6가':175, '삼선동5가':176, '보문동2가':177, '잠실동':178, 
  '신천동':179, '가락동':180, '문정동':181, '오금동':182, '송파동':183, '석촌동':184, '방이동':185, '풍납동':186, 
  '장지동':187, '마천동':188, '거여동':189, '신월동':190, '목동':191, '여의도동':192, '대림동':193, 
  '영등포동':194, '당산동4가':195, '문래동4가':196, '도림동':197, '당산동':198, '신길동':199, '당산동5가':200, 
  '당산동2가':201, '당산동3가':202, '양평동4가':203, '양평동5가':204, '영등포동7가':205, '문래동6가':206, 
  '문래동5가':207, '양평동2가':208, '영등포동1가':209, '양평동3가':210, '문래동3가':211, '당산동1가':212, 
  '양평동6가':213, '양평동1가':214, '영등포동8가':215, '영등포동3가':216, '문래동2가':217, '영등포동5가':218, 
  '당산동6가':219, '영등포동4가':220, '이태원동':221, '이촌동':222, '한남동':223, '한강로1가':224, '보광동':225, 
  '용산동5가':226, '원효로1가':227, '원효로4가':228, '한강로3가':229, '문배동':230, '서빙고동':231, '신계동':232, 
  '한강로2가':233, '동자동':234, '후암동':235, '청암동':236, '용산동2가':237, '도원동':238, '산천동':239, '효창동':240, 
  '용문동':241, '신창동':242, '청파동3가':243, '원효로3가':244, '불광동':245, '역촌동':246, '증산동':247, '진관동':248, 
  '구산동':249, '녹번동':250, '응암동':251, '갈현동':252, '대조동':253, '수색동':254, '연건동':255, '사직동':256, '무악동':257, 
  '평창동':258, '창신동':259, '내수동':260, '숭인동':261, '익선동':262, '명륜2가':263, '인의동':264, '행촌동':265, 
  '명륜1가':266, '동숭동':267, '필운동':268, '구기동':269, '교북동':270, '통인동':271, '황학동':272, '신당동':273, 
  '순화동':274, '회현동1가':275, '흥인동':276, '회현동2가':277, '중림동':278, '인현동2가':279, '만리동1가':280, 
  '남대문로5가':281, '충무로4가':282, '산림동':283, '필동1가':284, '상봉동':285, '면목동':286, '묵동':287, '신내동':289, 
  '중화동':290, '망우동':291}

pd.get_dummies(apart_df) # object 타입 dummy 변수화

# gu, dong 컬럼 df로 반환
pd.get_dummies(apart_df['gu'])
pd.get_dummies(apart_df['dong'])

# prefix로 변수명이 붙어서 반환
# Numeric으로 되어있지만 실제로는 범주형인 데이터인 경우 object type으로 변환하면서 dummy 변수화
pd.get_dummies(apart_df[['gu']])
pd.get_dummies(apart_df[['dong']])

apart_df['gu'] = apart_df['gu'].map(gu_dict)
apart_df['dong'] = apart_df['dong'].map(dong_dict)

gu                             object
address                        object
Apart                          object
pps                             int64
dong                           object
size                          float64
floor                           int64
year                            int64
long                          float64
lat                           float64
dist_from_mart.x              float64
dist_from_department          float64
dist_from_mart.y              float64
dist_from_highschool          float64
dist_from_elementaryschool    float64
dist_from_univ                float64
dist_from_middleschool        float64
dist_from_bus                 float64
dist_from_hospital            float64
dist_from_academy             float64
crime                           int64
arrest                          int64
foreigner                       int64
trash                         float64
cctv                            int64
dist_from_subway              float64
dist_from_ki

In [5]:
gu = pd.get_dummies(apart_df['gu'])
dong = pd.get_dummies(apart_df['dong'])

pd.concat([apart_df, gu], axis=1)
pd.concat([apart_df, dong], axis=1)

display(apart_df.gu) # 구 라벨링 출력 확인
display(apart_df.dong) # 동 라벨링 출력 확인

#del apart_df['gu']
#del apart_df['dong']

0         1
1         1
2         1
3         1
4         1
         ..
24725    25
24726    25
24727    25
24728    25
24729    25
Name: gu, Length: 24730, dtype: int64

0          1
1          2
2          2
3          3
4          4
        ... 
24725    286
24726    286
24727    286
24728    286
24729    285
Name: dong, Length: 24730, dtype: int64

In [6]:
apart_df.columns
apart_df.head()

gu       address   Apart   pps  dong   size  floor  year        long  \
0   1        언주로 21      시영  1612     1  51.18      2    32  127.055401   
1   1  남부순환로365길 16      대림   872     2  84.93      3    24  127.039692   
2   1       언주로 203    매봉삼성   859     2  84.95     20    17  127.049105   
3   1        자곡로 21  세곡푸르지오   896     3  84.83     13     4  127.094039   
4   1       일원로 127      가람  1057     4  84.95      3    23  127.084218   

         lat  ...  arrest  foreigner   trash  cctv  dist_from_subway  \
0  37.478663  ...    5905       9762  4009.8  4196       1195.866842   
1  37.486481  ...    5905       9762  4009.8  4196        541.484661   
2  37.489128  ...    5905       9762  4009.8  4196        302.676674   
3  37.466737  ...    5905       9762  4009.8  4196       2096.705257   
4  37.482700  ...    5905       9762  4009.8  4196        140.629048   

   dist_from_kinder  dist_from_park    out     in     popu  
0        442.874563      423.692220  30486  25725  1721505  
1        224.502273      238.720904  30486  25725  1721505  
2       1090.333414      697.114077  30486  25725  1721505  
3        352.911029     2719.411525  30486  25725  1721505  
4       1665.675267     2783.355902  30486  25725  1721505  

[5 rows x 31 columns]

In [9]:
#변수 축 나누기
y_df = apart_df.pps
X_df = apart_df.drop(['pps','Apart','address'], axis=1)

X_train, X_test, Y_train, Y_test = train_test_split(X_df,
                                                    y_df,
                                                    test_size = 0.3,
                                                    random_state = 2019)

In [10]:
# Robust Scaler
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
X_train_scale = scaler.fit_transform(X_train)

print('스케일 조정 후 : features MIN value : \n {}'.format(X_train_scale.min(axis=0)))
print('스케일 조정 후 : features MAX value : \n {}'.format(X_train_scale.max(axis=0)))


from sklearn.svm import SVC
X_train, X_test, Y_train, Y_test = train_test_split(
    X_df,
    y_df, 
    random_state=0)

svc = SVC()
svc.fit(X_train,Y_train)

print('test accuracy : %.3f'% svc.score(X_test, Y_test)) 

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scale =scaler.fit_transform(X_train) # 훈련쪽은 fit_transform

X_test_scale = scaler.transform(X_test) # 테스트쪽은 transform

svc.fit(X_train_scale,Y_train) # 스케일링 한 다음 fit 했을 경우

print('Scaled test accuracy :%.3f'%(svc.score(X_test_scale,Y_test)))


스케일 조정 후 : features MIN value : 
 [-0.91666667 -0.64102564 -2.76935776 -1.25       -1.46153846 -1.36427916
 -1.27211774 -1.18440788 -1.1432928  -1.18440788 -1.17260233 -1.36732923
 -0.9382716  -1.25       -0.875      -1.21568627 -0.9945852  -1.75560538
 -1.12312549 -0.88643183 -0.43109337 -0.86270492 -0.98564433 -1.19641197
 -1.1109041  -2.0059889  -1.89061238 -1.68665468]
스케일 조정 후 : features MAX value : 
 [ 1.08333333  1.83760684 13.47589046  6.875       2.53846154  1.08548652
  1.57726104  5.09670462  2.81863097  5.09670462  5.48079178  6.4056701
  3.38888889  7.71875     5.75        4.47058824 12.46398347  2.51270553
  2.01420679  4.82998111  1.13911203  2.75        8.31129838  4.39738571
  3.06354967  1.60677768  1.37001131  1.03264764]
test accuracy : 0.005
Scaled test accuracy :0.017


In [14]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

y = apart_df.pps
X = apart_df.drop(['pps','Apart','address'], axis=1)

# 독립변수 정규화(평균 0, 분산1인 표준정규분포)
X = preprocessing.StandardScaler().fit(X).transform(X) # StandardScaler : 표준정규분포

# 학습용 데이터와 평가용 데이터를 8:2로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

print(X_train.shape) # (19784, 28) 80% 데이터 갯수
print(X_test.shape) # (4946, 28) 20% 데이터 갯수

print(X.mean()) # 4.750797666675353e-15
print(X.std()) # 1.0
print(type(y_test)) # 시리즈 타입

# Decision Tree

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier() # 객체 생성
dt_model.fit(X_train, y_train) # 트레이닝 데이터로 학습
dt_pred = dt_model.predict(X_test) # 검증용 데이터로 예측

print(dt_pred[0:10]) # 예측값과
print(y_test.values[0:10]) # 실제 y 값을 대조하며 검증

accuracy = accuracy_score(y_test, dt_pred)
print('dt 예측 정확도:',accuracy) # 예측 정확도가 좋지 못하면 재개발 해야함

(19784, 28)
(4946, 28)
4.750797666675353e-15
1.0
<class 'pandas.core.series.Series'>
[566 400 634 687 567 514 376 733 386 413]
[598 522 648 696 581 597 331 754 365 330]
dt 예측 정확도: 0.0578245046502224


In [15]:
# Random Forest (투표를 해가며 결정해가는 방법)

from sklearn.ensemble import RandomForestClassifier #(분류기)

rf_model = RandomForestClassifier() # 객체 생성
rf_model.fit(X_train, y_train) # 학습을 시킨다. (트레이닝 데이터를 이용)
rf_pred = rf_model.predict(X_test) # 학습시킨 모델을 통해 예측한다. (검증용 데이터로)

rf_accuracy = accuracy_score(y_test, rf_pred) # 예측한 것과 실제 y값으로 비교해서 예측 정확도를 구한다.
print('rf 예측 정확도:', rf_accuracy) # 예측 정확도 출력

rf 예측 정확도: 0.061665992721391026


# 분석 시작

In [40]:
apart_df = pd.read_csv('C:/Users/hojys/workspace/ml_python/apart/K_20200425_sumVariable.csv', encoding='euc-kr')

# pps 데이터 범주화
apart_df['pps'] = pd.qcut(apart_df.pps, q=5, labels=['A', 'B', 'C', 'D', 'E'])

# 라벨링 함수 생성
def format_features(df):
    features = ['Apart','address','dong','gu', 'pps']
    for feature in features:
        le = LabelEncoder()
        df[feature] = le.fit_transform(df[feature])
    return df

apart_df = format_features(apart_df) # object 타입 변수 라벨링

display(apart_df.head()) # 데이터 출력 확인
display(apart_df.dtypes) # 컬럼별 데이터 타입 확인

gu  address  Apart  pps  dong   size  floor  year        long        lat  \
0   0     2842   1958    4     7  51.18      2    32  127.055401  37.478663   
1   0      673    584    4    53  84.93      3    24  127.039692  37.486481   
2   0     2841   1118    4    53  84.95     20    17  127.049105  37.489128   
3   0     3427   1852    4   140  84.83     13     4  127.094039  37.466737   
4   0     3424    109    4   220  84.95      3    23  127.084218  37.482700   

   ...  arrest  foreigner   trash  cctv  dist_from_subway  dist_from_kinder  \
0  ...    5905       9762  4009.8  4196       1195.866842        442.874563   
1  ...    5905       9762  4009.8  4196        541.484661        224.502273   
2  ...    5905       9762  4009.8  4196        302.676674       1090.333414   
3  ...    5905       9762  4009.8  4196       2096.705257        352.911029   
4  ...    5905       9762  4009.8  4196        140.629048       1665.675267   

   dist_from_park    out     in     popu  
0      423.692220  30486  25725  1721505  
1      238.720904  30486  25725  1721505  
2      697.114077  30486  25725  1721505  
3     2719.411525  30486  25725  1721505  
4     2783.355902  30486  25725  1721505  

[5 rows x 31 columns]

gu                              int32
address                         int32
Apart                           int32
pps                             int32
dong                            int32
size                          float64
floor                           int64
year                            int64
long                          float64
lat                           float64
dist_from_mart.x              float64
dist_from_department          float64
dist_from_mart.y              float64
dist_from_highschool          float64
dist_from_elementaryschool    float64
dist_from_univ                float64
dist_from_middleschool        float64
dist_from_bus                 float64
dist_from_hospital            float64
dist_from_academy             float64
crime                           int64
arrest                          int64
foreigner                       int64
trash                         float64
cctv                            int64
dist_from_subway              float64
dist_from_ki

In [41]:
# 축 분류
y_df = apart_df.pps
X_df = apart_df.drop(['pps'], axis=1)

#데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=11)

#객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

#검증모델 호출
from sklearn.model_selection import KFold

# KFold 검증 실행
def exec_kfold(clf, folds=5):      
    kfold = KFold(n_splits=folds)  
    scores = []
    
    for iter_count, (train_index, test_index) \
    in enumerate(kfold.split(X_df)):            
        X_train, X_test = X_df.values[train_index], X_df.values[test_index]
        y_train, y_test = y_df.values[train_index], y_df.values[test_index]
        
        clf.fit(X_train, y_train)                 
        predictions = clf.predict(X_test)  
        accuracy = accuracy_score(y_test, predictions)
        scores.append(accuracy)                      
        print('교차 검증 {0}정확도: {1:.4f}'.format(iter_count, accuracy))
        
        
    mean_score = np.mean(scores)
    print('평균 정확도: {0: .4f}'.format(mean_score))
        
# 메소드 실행(정확도 추출)
exec_kfold(dt_clf, folds=5)

교차 검증 0정확도: 0.4228
교차 검증 1정확도: 0.2703
교차 검증 2정확도: 0.4207
교차 검증 3정확도: 0.3261
교차 검증 4정확도: 0.2457
평균 정확도:  0.3371


In [42]:
# cross_val_scores
from sklearn.model_selection import cross_val_score

scores = cross_val_score(dt_clf, X_df, y_df, cv=10)
for iter_count, accuracy in enumerate(scores):
    print('DT 교차 검증 {0} 정확도: {1:.4f}'.format(iter_count, accuracy))
    
print('DT 평균 정확도:{0:.4f}'.format(np.mean(scores)))

DT 교차 검증 0 정확도: 0.2936
DT 교차 검증 1 정확도: 0.4695
DT 교차 검증 2 정확도: 0.4715
DT 교차 검증 3 정확도: 0.4497
DT 교차 검증 4 정확도: 0.3704
DT 교차 검증 5 정확도: 0.4755
DT 교차 검증 6 정확도: 0.4036
DT 교차 검증 7 정확도: 0.4108
DT 교차 검증 8 정확도: 0.4816
DT 교차 검증 9 정확도: 0.3029
DT 평균 정확도:0.4129


In [43]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

#파라미터 생성
parameters = {'max_depth':[2,3,5,10], 'min_samples_split':[2,3,5], 'min_samples_leaf':[1,5,8]}

#객체 생성
grid_dclf = GridSearchCV(dt_clf, param_grid=parameters, scoring='accuracy', cv=5, refit=True) 

# 학습
grid_dclf.fit(X_train, y_train) 

print('GridSearchCV DT 최적 하이퍼 파라미터:', grid_dclf.best_params_) 
print('GridSearchCV DT 최고 정확도:', grid_dclf.best_score_)

best_dclf = grid_dclf.best_estimator_
display(best_dclf) # 출력

# DT 예측 데이터
dpredictions = best_dclf.predict(X_test) 
accuracy = accuracy_score(y_test, dpredictions)
print('Dicision Tree GSCV 예측 정확도 : ', accuracy)

GridSearchCV DT 최적 하이퍼 파라미터: {'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 3}
GridSearchCV DT 최고 정확도: 0.6853520900744685


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=10, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=11, splitter='best')

Dicision Tree GSCV 예측 정확도 :  0.6839870602507077


In [45]:
#Random Forest 
rf_clf = RandomForestClassifier(random_state=11)

#메소드 실행
exec_kfold(rf_clf, folds=5)
print('\n')

# cross_val_scores
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf_clf, X_df, y_df, cv=10)
for iter_count, accuracy in enumerate(scores):
    print('RF 교차 검증 {0} 정확도: {1:.4f}'.format(iter_count, accuracy))
    
print('RF 평균 정확도:{0:.4f}'.format(np.mean(scores)))

교차 검증 0정확도: 0.3132
교차 검증 1정확도: 0.4300
교차 검증 2정확도: 0.5210
교차 검증 3정확도: 0.4135
교차 검증 4정확도: 0.2942
평균 정확도:  0.3944

RF 교차 검증 0 정확도: 0.3720
RF 교차 검증 1 정확도: 0.4679
RF 교차 검증 2 정확도: 0.4533
RF 교차 검증 3 정확도: 0.4387
RF 교차 검증 4 정확도: 0.3494
RF 교차 검증 5 정확도: 0.4945
RF 교차 검증 6 정확도: 0.3643
RF 교차 검증 7 정확도: 0.4205
RF 교차 검증 8 정확도: 0.4691
RF 교차 검증 9 정확도: 0.3421
RF 평균 정확도:0.4172


In [46]:
#GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

parameters = {'n_estimators':[50,100,200],'max_depth':[2,3,5],'min_samples_leaf':[1,5,8]}

grid_rflf = GridSearchCV(rf_clf, param_grid=parameters, scoring='accuracy', cv=5, refit=True) 

grid_rflf.fit(X_train, y_train) # 학습

print('GridSearchCV RF 최적 하이퍼 파라미터:', grid_rflf.best_params_) 
print('GridSearchCV RF 최고 정확도:', grid_rflf.best_score_) 

best_rflf = grid_rflf.best_estimator_
display(best_rflf)

# 예측값 출력
rpredictions = best_rflf.predict(X_test)
accuracy = accuracy_score(y_test, rpredictions)
print('Random Forest GSCV 예측 정확도 : ', accuracy)

GridSearchCV RF 최적 하이퍼 파라미터: {'max_depth': 5, 'min_samples_leaf': 1, 'n_estimators': 200}
GridSearchCV RF 최고 정확도: 0.5393750384888308


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=5, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=11, verbose=0,
                       warm_start=False)

Random Forest GSCV 예측 정확도 :  0.5244642135058634


In [47]:
# Logistic Regression
import warnings
warnings.filterwarnings('ignore')

#객체 생성
lr_clf = LogisticRegression(random_state=11)

#메소드 실행
exec_kfold(lr_clf, folds=5)
print()

# cross_val_scores
from sklearn.model_selection import cross_val_score

scores = cross_val_score(lr_clf, X_df, y_df, cv=10)
for iter_count, accuracy in enumerate(scores):
    print('LR 교차 검증 {0} 정확도: {1:.4f}'.format(iter_count, accuracy))
    
print('LR 평균 정확도:{0:.4f}'.format(np.mean(scores)))

교차 검증 0정확도: 0.5093
교차 검증 1정확도: 0.3073
교차 검증 2정확도: 0.3773
교차 검증 3정확도: 0.1686
교차 검증 4정확도: 0.2950
평균 정확도:  0.3315

LR 교차 검증 0 정확도: 0.3676
LR 교차 검증 1 정확도: 0.2936
LR 교차 검증 2 정확도: 0.4909
LR 교차 검증 3 정확도: 0.3182
LR 교차 검증 4 정확도: 0.4181
LR 교차 검증 5 정확도: 0.4772
LR 교차 검증 6 정확도: 0.2074
LR 교차 검증 7 정확도: 0.3801
LR 교차 검증 8 정확도: 0.3817
LR 교차 검증 9 정확도: 0.2459
LR 평균 정확도:0.3581


In [48]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

parameters = {'penalty':['l2','l1'],'C':[0.01,0.1,1,1,5,10]}

# 객체 생성(5번 반복)
grid_lrlf = GridSearchCV(lr_clf, param_grid=parameters, scoring='accuracy', cv=5, refit=True) 

grid_lrlf.fit(X_train, y_train) # 학습

print('GridSearchCV LR 최적 하이퍼 파라미터:', grid_lrlf.best_params_) 
print('GridSearchCV LR 최고 정확도:', grid_lrlf.best_score_) 

best_lrlf = grid_lrlf.best_estimator_
display(best_lrlf)

# 예측 출력
lpredictions = best_lrlf.predict(X_test)
accuracy = accuracy_score(y_test, lpredictions)
print('Logistic Regression GSCV 예측 정확도 :', accuracy)

GridSearchCV LR 최적 하이퍼 파라미터: {'C': 0.1, 'penalty': 'l2'}
GridSearchCV LR 최고 정확도: 0.40714698938768706


LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=11, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

Logistic Regression GSCV 예측 정확도 : 0.3968863728265265


In [49]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=11)

# 스케일링 & 학습
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# 객체 생성
mlp_clf =MLPClassifier(random_state=10)

# MLP알고리즘의 히든레이어 노드를 10개씩 3계층으로 구성
mlp = MLPClassifier(activation='relu',\
                    alpha=0.0001,\
                    batch_size='auto',\
                    beta_1=0.9,\
                    beta_2=0.999,\
                    early_stopping=False,\
                    epsilon=1e-08,\
                    hidden_layer_sizes=(30, 30, 30),\
                    learning_rate='constant', \
                    learning_rate_init=0.001, max_iter=200,\
                    momentum=0.9, nesterovs_momentum=True,\
                    power_t=0.5, random_state=None,\
                    shuffle=True, solver='adam', \
                    tol=0.0001, validation_fraction=0.1, \
                    verbose=False, warm_start=False)

# 학습
mlp.fit(X_train, y_train)

# 예측 출력
predictions = mlp.predict(X_test)

print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[747 198  29   3   1]
 [153 647 157  22   5]
 [ 10 165 639 176  12]
 [  3   5 132 745  92]
 [  8   0   3  75 919]]
              precision    recall  f1-score   support

           0       0.81      0.76      0.79       978
           1       0.64      0.66      0.65       984
           2       0.67      0.64      0.65      1002
           3       0.73      0.76      0.75       977
           4       0.89      0.91      0.90      1005

    accuracy                           0.75      4946
   macro avg       0.75      0.75      0.75      4946
weighted avg       0.75      0.75      0.75      4946



In [50]:
import warnings
warnings.filterwarnings('ignore')
parameters={'alpha': [1,10,0.1],'activation': ["logistic", "relu"]}

grid_mlplf = GridSearchCV(mlp_clf, param_grid=parameters, n_jobs=-1,verbose=2, scoring='accuracy', cv=5, refit=True) 
# refit=True는 최적으로 된 하이퍼 파라미터를 반영하겠다는 의미

grid_mlplf.fit(X_train, y_train) # 학습

print('GridSearchCV mlp 최적 하이퍼 파라미터:', grid_mlplf.best_params_)
print('GridSearchCV mlp 최고 정확도:', grid_mlplf.best_score_)

best_mlplf = grid_mlplf.best_estimator_
mlppredictions = best_mlplf.predict(X_test)
accuracy = accuracy_score(y_test, mlppredictions)
print('dt 예측 정확도 : ', accuracy)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  23 out of  30 | elapsed:   39.5s remaining:   12.0s
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:   58.4s finished


GridSearchCV mlp 최적 하이퍼 파라미터: {'activation': 'relu', 'alpha': 0.1}
GridSearchCV mlp 최고 정확도: 0.7387788033800156
dt 예측 정확도 :  0.7456530529720987
